### ISSUE TITLE
datumEither.fromEither should probably accept Either

### ISSUE THREAD

**Issue by ljani** [nullpub/datum#12]
Comparing [`datumEither.fromEither(e: Lazy<Either<E, A>>)`](https://github.com/nullpub/datum/blob/39886edb1bb6c934803f83911b08d2854ecc6067/docs/modules/DatumEither.ts.md#fromeither) to [`taskEither.fromEither(ma: E.Either<E, A>)`](https://github.com/gcanti/fp-ts/blob/820f47bd06fde88bdb2d746957ac1368c23a2f42/docs/modules/TaskEither.ts.md#fromeither), I cannot help but wonder if the signature should directly accept `Either<E, A>` and not a `Lazy<Either<E, A>>`. Any thoughts?

Here's my use case:
```typescript
const task = pipe(
    id,
    getEntity, // returns TaskEither<E, A>
    T.map(
        flow(
            // Currently I need to do:
            // F.constant, ie. a => () => a,
            datumEither.fromEither,
            datumEither.mapLeft(mapError), // E -> G
            datumEither.chain(mapResponse) // A -> <G, B>
        )
    ),
    T.map((result: DatumEither<G, B>): void => {
        // Effect in outside of my functional bubble 
    })
);
task();
```

As I'm still learning, please let me know, if there is a better way to combine `TaskEither` and `DatumEither`.

**Comment by ljani** [comment]
While we are at it, the constructors should probably have the other type as well to make composing easier, ie.:

```typescript
export declare const success: <E = never, A = never>(a: A) => Datum<Either<E, A>>;
export declare const failure: <E = never, A = never>(e: E) => Datum<Either<E, A>>;
```

See [`TaskEither.right`](https://gcanti.github.io/fp-ts/modules/TaskEither.ts.html#right) (and [`TaskEither.of`](https://gcanti.github.io/fp-ts/modules/TaskEither.ts.html#of)).

**Comment by baetheus** [comment]
Thanks for the issue. I've been working on a deno port of fp-ts and have let datum languish (although it is pretty stable so languishing isn't bad). I've introduced a new `fromEither2` function that doesn't take lazy inputs. I've deprecated both fromEither and fromEither2 until the next major release (which will probably be a partial rewrite with better organization).

I've also expanded the types for success and failure. I'm hopeful that that nobody was manually setting types before, as this is a breaking type change. Since the previous functions inferred well it seems unlikely though.

I also needed DatumEither to be traversable today (for use with monocle-ts) so I implemented that type class as well as Foldable.

**Comment by ljani** [comment]
Thanks for the fix. [The docs](https://github.com/nullpub/datum/blob/0b2539f74d87f4cd3ee8d71de42b07de33d01541/docs/modules/DatumEither.ts.md) seem to contain a lot of `any`s now, is that intended?

**Comment by baetheus** [comment]
No! It looks like there was a change in the docs-ts package such that it no longer parses the constant arrow function signatures completely. I'll look into it.

**Comment by baetheus** [comment]
Looks like the parsing of arrow functions works fine, it's type only imports. I don't have the time to dig into the docs-ts code to find out why it casts type only imports so for now I've just removed them.

**Comment by baetheus** [comment]
If you've got some free time and are learning fp stuff, I have a port of fp-ts, monocle-ts, and io-ts at [nullpub/hkts](https://github.com/nullpub/hkts) that I could use help dogfooding.

**Comment by ljani** [comment]
Looks interesting! However, I'm only targeting browsers and thus I haven't tried Deno at all.
